name             'tomee'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures tomee'
long_description 'Installs/Configures tomee'
version          '0.1.0'
